USE [master]
GO

/****** Object:  Database [R49_MyEcommerceDB]    Script Date: 1/29/2023 2:44:34 PM ******/
CREATE DATABASE [R49_MyEcommerceDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'R49_MyEcommerceDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\R49_MyEcommerceDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'R49_MyEcommerceDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\R49_MyEcommerceDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [R49_MyEcommerceDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [R49_MyEcommerceDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [R49_MyEcommerceDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [R49_MyEcommerceDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [R49_MyEcommerceDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [R49_MyEcommerceDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [R49_MyEcommerceDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [R49_MyEcommerceDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [R49_MyEcommerceDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [R49_MyEcommerceDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [R49_MyEcommerceDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [R49_MyEcommerceDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [R49_MyEcommerceDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [R49_MyEcommerceDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [R49_MyEcommerceDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [R49_MyEcommerceDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [R49_MyEcommerceDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [R49_MyEcommerceDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [R49_MyEcommerceDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [R49_MyEcommerceDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [R49_MyEcommerceDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [R49_MyEcommerceDB] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [R49_MyEcommerceDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [R49_MyEcommerceDB] SET RECOVERY FULL 
GO

ALTER DATABASE [R49_MyEcommerceDB] SET  MULTI_USER 
GO

ALTER DATABASE [R49_MyEcommerceDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [R49_MyEcommerceDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [R49_MyEcommerceDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [R49_MyEcommerceDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [R49_MyEcommerceDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [R49_MyEcommerceDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [R49_MyEcommerceDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [R49_MyEcommerceDB] SET  READ_WRITE 
GO


